### ISSUE TITLE
Unable to build on macOs mojave

### ISSUE THREAD

**Issue by stefanoborini** [XiaoouPan/conquer#1]
The package cannot build on macOs mojave. The compiler uses the -openmp switch, which is not available on stock Apple llvm

**Comment by XiaoouPan** [comment]
Sorry for the late reply. Do you mean R >= 4.0.0? I just notice that this version of R loses the ability to use OpenMP without a custom setup.

**Comment by stefanoborini** [comment]
We use R 3.6.

**Comment by XiaoouPan** [comment]
Sorry but I just tried installing it on a macOS Mojave 10.14.4 with R 3.6.1, and it works fine. 
Could this following page be helpful? 
https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos-before-r-4.0.0/
