### ISSUE TITLE
minimum R version

### ISSUE THREAD

**Issue by dchiu911** [XiaoouPan/conquer#3]
Is it possible to relax the minimum version to `Depends: R (>= 3.5.0)`? Your package is a new `Imports` for `quantreg` and I was hoping to continue to use the newest `quantreg` for R 3.5.3.

**Comment by XiaoouPan** [comment]
Thank you for your feedback. I just made an update but you may have to wait a few days, since the CRAN submission team is on vacation so I can't submit the updated package until Aug 24..
