### ISSUE TITLE
clang error

### ISSUE THREAD

**Issue by lurebgi** [XiaoouPan/conquer#4]
R version 3.5.0

> install.packages("conquer")
Installing package into ‘/Users/luohao/Dropbox/bioinformatic_documents/R/R_lib’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need compilation of C/C++/Fortran:
  ‘conquer’
Do you want to attempt to install these from sources? (Yes/no/cancel) Yes
installing the source package ‘conquer’

trying URL 'https://cran.wu.ac.at/src/contrib/conquer_1.2.1.tar.gz'
Content type 'application/x-gzip' length 23869 bytes (23 KB)
==================================================
downloaded 23 KB
* installing *source* package ‘conquer’ ...
** package ‘conquer’ successfully unpacked and MD5 sums checked
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/luohao/Dropbox/bioinformatic_documents/R/R_lib/Rcpp/include" -I"/Users/luohao/Dropbox/bioinformatic_documents/R/R_lib/RcppArmadillo/include" -I/usr/local/include  -fopenmp  -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘conquer’

**Comment by XiaoouPan** [comment]
Sorry for this. At this point, it's still a source package on CRAN, and the error is because Apple-provided clang does not support OpenMP by default.

The binary package should be ready in a few days. I'm also waiting for a notice from CRAN.

**Comment by yumh0811** [comment]
> Sorry for this. At this point, it's still a source package on CRAN, and the error is because Apple-provided clang does not support OpenMP by default.
> 
> The binary package should be ready in a few days. I'm also waiting for a notice from CRAN.


Hi Xiaoou,

When I tried to install the package 'conquer', I still came across this problem as below. May I know when the error can be fixed? Besides, I tried to install the old versions and it still failed. May I know any other alternative solutions?

```
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [conquer.so] Error 1
ERROR: compilation failed for package ‘conquer’
```

**Comment by XiaoouPan** [comment]
> 

We recently submitted a new version (1.3.0) to CRAN, and it's still a source version.

When you install the package, you'll be asked: "There is a binary version available but the source version is later. Do you want to install from sources the package which needs compilation?" Select no.

**Comment by XiaoouPan** [comment]
> > Sorry for this. At this point, it's still a source package on CRAN, and the error is because Apple-provided clang does not support OpenMP by default.
> > The binary package should be ready in a few days. I'm also waiting for a notice from CRAN.
> 
> Hi Xiaoou,
> 
> When I tried to install the package 'conquer', I still came across this problem as below. May I know when the error can be fixed? Besides, I tried to install the old versions and it still failed. May I know any other alternative solutions?
> 
> ```
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
> ld: library not found for -lgfortran
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [conquer.so] Error 1
> ERROR: compilation failed for package ‘conquer’
> ```

We recently submitted a new version (1.3.0) to CRAN, and it's still a source version.

When you install the package, you'll be asked: "There is a binary version available but the source version is later. Do you want to install from sources the package which needs compilation?" Select no.
