### ISSUE TITLE
Eliminate dependency to {caret}

### ISSUE THREAD

**Issue by phgrosjean** [XiaoouPan/conquer#5]
There is a dependency to {caret} that installs a lot of unwanted packages in cascade. The dependency is just for using its `createFolds()` function. The way it is used, (`folds = createFolds(Y, kfolds, FALSE)`, line 385 in smqr.R, it seems that it could be replaced by something like:

```
len <- length(Y)
folds <- sample(rep(1:kfolds, ceiling(len/kfolds)), len))
```

This way, you could get rid of the dependency to {caret} and get a cleaner installation.

**Comment by XiaoouPan** [comment]
> There is a dependency to {caret} that installs a lot of unwanted packages in cascade. The dependency is just for using its `createFolds()` function. The way it is used, (`folds = createFolds(Y, kfolds, FALSE)`, line 385 in smqr.R, it seems that it could be replaced by something like:
> 
> ```
> len <- length(Y)
> folds <- sample(rep(1:kfolds, ceiling(len/kfolds)), len))
> ```
> 
> This way, you could get rid of the dependency to {caret} and get a cleaner installation.

Thank you for your advice and you're right! We use {caret} to create folds for cross-validation. Let me quickly modify this part.
