### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by slancast** [XiaoouPan/conquer#6]
Hi,
I'm running into an error compiling conquer. Is there an easy fix I'm missing? See error report below.

ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [conquer.so] Error 1
ERROR: compilation failed for package ‘conquer’

**Comment by XiaoouPan** [comment]
> Hi, I'm running into an error compiling conquer. Is there an easy fix I'm missing? See error report below.
> 
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0' ld: warning: directory not found for option '-L/usr/local/gfortran/lib' ld: library not found for -lgfortran clang: error: linker command failed with exit code 1 (use -v to see invocation) make: *** [conquer.so] Error 1 ERROR: compilation failed for package ‘conquer’

Hi,

This is because the most updated version 1.3.0 on CRAN is still a source package.

When you install the package, you'll be asked: "There is a binary version available but the source version is later. Do you want to install from sources the package which needs compilation?" Select no.
